apiVersion: v1
kind: Secret
metadata:
  name: dockercreds
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: ygu26
  password: 1ee45eb1-df88-406c-a182-d56cb010781c
