apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-sample-git
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/yguionnet/nodejs-sample.git
