apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nodejs-sample-pipeline-run
spec:
  serviceAccountName: dockerhub-service
  pipelineRef:
    name: nodejs-sample-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: nodejs-sample-git
    - name: web-image
      resourceRef:
        name: nodejs-sample-image
