apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: service-using-kubectl
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(params.path)"
        - "--validate=false"
